In [2]:
import pandas as pd

students = [('Ana',23,'San Jose','A'),
            ('Esteban',22,'Heredia','B'),
            ('Juan',22,'Cartago','A'),
            ('Karla',22,'Limon','A'),
            ('Ernesto',21,'Heredia','B')
            ]
df = pd.DataFrame(students,columns =['Nombre','Edad','Ciudad','Seccion'])
print(df)

    Nombre  Edad    Ciudad Seccion
0      Ana    23  San Jose       A
1  Esteban    22   Heredia       B
2     Juan    22   Cartago       A
3    Karla    22     Limon       A
4  Ernesto    21   Heredia       B

In [3]:
def buscar(df, columna, valor):
    return df[df[columna] == valor]

resultado = buscar(df, 'Ciudad', 'Heredia')
print(resultado)

    Nombre  Edad   Ciudad Seccion
1  Esteban    22  Heredia       B
4  Ernesto    21  Heredia       B

In [4]:
def getIndexes(dfObj,value):
  listOfPos = []
  result = dfObj.isin([value])
  seriesObj = result.any()
  columnNames = list(seriesObj [seriesObj == True].index)

  for col in columnNames:
    rows = list(result[col][result[col] == True].index)

    for row in rows:
      listOfPos.append((row, col))

  return listOfPos

getIndexes(df,'A')

[(0, 'Seccion'), (2, 'Seccion'), (3, 'Seccion')]

In [7]:
listofPositions = getIndexes(df,22)

print('Index Positiosn of 22 in Dataframe :')

for i in range(len(listofPositions)):
  print(listofPositions[i])

Index Positiosn of 22 in Dataframe :
(1, 'Edad')
(2, 'Edad')
(3, 'Edad')